import type { Metadata } from "next";
import "./globals.css";
import ProgressProviders from "@/providers/ProgressProvider";

export const metadata: Metadata = {
  title: "Admin Panel | X-Obese",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased`}>
        <ProgressProviders>{children}</ProgressProviders>
      </body>
    </html>
  );
}
